### Register

POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name":"Manoj",
    "email":"chennupatimanojkumar2@gmail.com",
    "password":"suhana",
    "role":"USER",
    "phone":"9398599175",
    "address":{
        "street":"hi",
        "city":"hello",
        "state":"hey",
        "country":"heyyyy",
        "zipCode":"Hello Friends"

    }
}

### Login

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email":"chennupatimanojkumar2@gmail.com",
    "password":"suhana"
}
