import {
  Home,
  ShoppingCart,
  Package,
  Settings,
  User,
  Search,
  X,
  Plus,
  Minus,
  Trash2,
  Check,
  AlertTriangle,
  Info,
  Tag,
  Star,
  Heart,
  MapPin,
  Mail,
  Lock,
  Eye,
  EyeOff,
  ShoppingBag,
  Calendar,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  Loader2,
  Shield,
  LogOut,
  Building2,
  Map,
  Globe,
  Hash,
  CreditCard,
  DollarSign,
  CheckCircle2,
  Truck,
  Gift,
  RefreshCw,
  Phone,
  Key,
  Edit,
  LayoutDashboard,
  Package2,
  Users,
  TrendingUp,
  BarChart3,
  Filter,
  SlidersHorizontal,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Bell,
  Bookmark,
  Share2,
  Download,
  Upload,
  Camera,
  Image,
  Link,
  Copy,
  ExternalLink,
  HelpCircle,
  ZoomIn,
  ZoomOut,
  RotateCw,
  Zap,
  MessageSquare,
  Send,
} from 'lucide-react'

const iconMap = {
  home: Home,
  cart: ShoppingCart,
  package: Package,
  settings: Settings,
  user: User,
  search: Search,
  close: X,
  plus: Plus,
  minus: Minus,
  trash: Trash2,
  check: Check,
  alert: AlertTriangle,
  info: Info,
  tag: Tag,
  star: Star,
  heart: Heart,
  mapPin: MapPin,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  shopping: ShoppingBag,
  shoppingBag: ShoppingBag,
  calendar: Calendar,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  loader: Loader2,
  shield: Shield,
  logOut: LogOut,
  building: Building2,
  map: Map,
  globe: Globe,
  hash: Hash,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  checkCircle: CheckCircle2,
  truck: Truck,
  gift: Gift,
  refreshCw: RefreshCw,
  phone: Phone,
  key: Key,
  edit: Edit,
  dashboard: LayoutDashboard,
  package2: Package2,
  users: Users,
  trending: TrendingUp,
  barChart: BarChart3,
  filter: Filter,
  sliders: SlidersHorizontal,
  bell: Bell,
  bookmark: Bookmark,
  share: Share2,
  download: Download,
  upload: Upload,
  camera: Camera,
  image: Image,
  link: Link,
  copy: Copy,
  externalLink: ExternalLink,
  help: HelpCircle,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  rotate: RotateCw,
  zap: Zap,
  message: MessageSquare,
  send: Send,
}

const Icon = ({ name, size = 20, className = '', style = {}, strokeWidth = 1.75 }) => {
  const LucideIcon = iconMap[name] || Info
  const isLoader = name === 'loader'

  return (
    <span
      className={`icon ${className}`}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        ...(isLoader ? { animation: 'spin 1s linear infinite' } : {}),
        ...style,
      }}
    >
      <LucideIcon size={size} strokeWidth={strokeWidth} />
    </span>
  )
}

export default Icon
